Added caroline feature
Carolinebakeneko/TaxCalculatorService pull request #1
Opened 2023-05-02 10:01 UTC by Carolinebakeneko

add if for o to 13999

2023-05-02 14:42 UTC, Mithila-Kuda requested changes
Hey, please run the test. I believe that will give an error. Because expected value be( income *(10.5/100).

But ur code it says ( 15/100).

Therefore please do a test

2023-05-02 14:42 UTC, Mithila-Kuda commented on tax-calculator/src/main/java/com/tech/dojo/tax/calculator/components/TaxCalculatorComponentsImp.java
> +        if (income>0 && income<=13999) return income * (15 / 100);
Noted. But this bracket already exists.

2023-05-02 14:42 UTC, Mithila-Kuda commented on tax-calculator/src/main/java/com/tech/dojo/tax/calculator/components/TaxCalculatorComponentsImp.java
>          return income * (10.5/100);
This is is the outcome of the 0 to 14000 tax bracket.

2023-05-10 09:13 UTC, Ssolomonella approved these changes

2023-05-10 10:36 UTC, Mithila-Kuda approved these changes

2023-05-10 10:36 UTC, merged